import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mabryPro = localFont({
  src: [
    {
      path: "./fonts/MabryProRegular.woff",
      weight: "400",
    },
    {
      path: "./fonts/MabryProBold.woff",
      weight: "600",
    },
  ],
  variable: "--font-mabry-pro",
  weight: "400,600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mabryPro.variable} font-mabry-pro antialiased`}>
        {children}
      </body>
    </html>
  );
}
