export const categoriesList = [
    {
        name: "T-Shirts",
        measurements: [
            "Chest",
            "Length",
            "Shoulder Width",
            "Sleeve Length"
        ],
        material: ["100% Cotton", "Cotton Blend", "Polyester", "Organic Cotton", "Recycled Polyester"],
        subcategories: [
            "Basic T-Shirts",
            'Ringer T-Shirts',
            "Plain T-Shirts",
            "Graphic T-Shirts",
            "Long Sleeve T-Shirts",
            "Striped T-Shirts",
            "Henley T-Shirts",
            "Pocket T-Shirts",
            "Oversized T-Shirts",
            "Round Neck T-Shirts",
            "V-Neck T-Shirts",
            "Crew Neck T-Shirts"
        ],
        tags: [
            "Casual",
            "Everyday Wear",
            "Streetwear",
            "Lightweight",
            "Comfortable",
            "Layering Piece",
            "Breathable",
            "Minimalist",
            "Summer Essential",
            "Vintage"
        ],
    },
    {
        name: "Shirts",
        measurements: [
            "Collar",
            "Chest",
            "Waist",
            "Length",
            "Shoulder Width",
            "Sleeve Length"
        ],
        material: ["Cotton", "Polyester", "Linen", "Silk", "Oxford Fabric", "Chambray"],
        subcategories: [
            "Formal Shirts",
            "Casual Shirts",
            "Dress Shirts",
            "Flannel Shirts",
            "Plain Shirts",
            "Printed Shirts",
            "Checkered Shirts",
            "Short Sleeve Shirts",
            "Denim Shirts",
            "Linen Shirts",
            "Mandarin Collar Shirts",
        ],
        tags: [
            "Formal",
            "Smart Casual",
            "Button-Up",
            "Office Wear",
            "Versatile",
            "Breathable",
            "Stylish",
            "Comfort Fit",
            "Slim Fit",
        ],
    },
    {
        name: "Hoodies & Sweatshirts",
        measurements: [
            "Chest",
            "Length",
            "Sleeve Length",
            "Shoulder Width"
        ],
        material: ["Cotton", "Fleece", "Polyester", "Sherpa", "Knitted Fabric"],
        subcategories: [
            "Pullover Hoodies",
            "Sweatshirts",
            "Zip-Up Hoodies",
            "Fleeces",
            "Pullover Hoodies",
            "Crewneck Sweatshirts",
            "Graphic Sweatshirts",
            "Oversized Hoodies",
            "Fleece Sweatshirts",
            "Cropped Sweatshirts"
        ],
        tags: [
            "Casual",
            "Cozy",
            "Layering",
            "Streetwear",
            "Athleisure",
            "Warm",
            "Comfortable Fit",
            "Winter Wear",
            "Crewneck Sweatshirts",
        ],
    },
    {
        name: "Jackets & Coats",
        measurements: [
            "Chest",
            "Length",
            "Shoulder Width",
            "Sleeve Length"
        ],
        material: ["Wool", "Polyester", "Denim", "Leather", "Nylon", "Down Fill"],
        subcategories: [
            "Puffer Jackets",
            "Denim Jackets",
            "Leather Jackets",
            "Bomber Jackets",
            "Denim Coats",
            "Blazers",
            "Rain Coats",
            "Winter Coats",
            "Windbreakers",
            "Varsity Jackets",
        ],
        tags: [
            "Outerwear",
            "Weather Resistant",
            "Layering",
            "Warmth",
            "Stylish",
            "Durable",
            "Winter Wear",
        ],
    },
    {
        name: "Jeans",
        measurements: [
            "Waist",
            "Hip",
            "Inseam",
            "Outseam",
            "Thigh",
            "Leg Opening"
        ],
        material: ["100% Denim", "Stretch Denim", "Cotton", "Selvedge Denim"],
        subcategories: [
            "Straight Jeans",
            "Ripped Jeans",
            "Skinny Jeans",
            "Relaxed Fit Jeans",
            "Bootcut Jeans",
            "Slim Jeans",
            "Flared Jeans",
            "Boyfriend Jeans",
            "Mom Jeans",
            "High-Waisted Jeans",
            "Distressed Jeans",
            "Baggy Jeans"
        ],
        tags: [
            "Casual",
            "Everyday Wear",
            "Durable",
            "Trendy",
            "Versatile",
            "Street Style",
            "Comfortable Fit",
            "Stretch",
            "Vintage Wash",
            "Dark Wash",
            "Ripped",
            "Classic",
        ],
    },
    {
        name: "Trousers",
        measurements: [
            "Waist",
            "Hip",
            "Inseam",
            "Outseam",
            "Thigh",
            "Leg Opening"
        ],
        material: ["Cotton", "Linen", "Polyester", "Stretch Blend"],
        subcategories: [
            "Cargo",
            "Chinos",
            "Joggers",
            "Formal Trousers",
            "Wide-Leg Trousers",
            "Slim Fit Pants",
            "Pleated Trousers",
            "Linen Pants",
            "Cropped Pants",
            "Leather Pants",
            "Palazzo Pants",
        ],
        tags: [
            "Smart Casual",
            "Chic",
            "Lightweight",
            "Versatile",
            "Comfortable",
            "Stylish",
            "Durable",
            "Utility",
            "High Fashion",
            "Wrinkle-Resistant"
        ],
    },
    {
        name: "Skirts",
        measurements: [
            "Waist",
            "Hip",
            "Length"
        ],
        material: ["Cotton", "Polyester", "Linen", "Silk"],
        subcategories: [
            "Maxi Skirts",
            "Midi Skirts",
            "Mini Skirts",
            "Wrap Skirts",
            "Pencil Skirts",
            "Pleated Skirts",
            "A-Line Skirts",
            "Denim Skirts",
            "Tiered Skirts",
            "Bodycon Skirts"
        ],
        tags: [
            "Fashionable",
            "Chic",
            "Lightweight",
            "Versatile",
            "Everyday Wear",
            "Stylish",
            "Office Wear",
            "Flowy",
            "Formal",
            "Vintage",
        ],
    },
    {
        name: "Sweaters",
        measurements: [
            "Chest",
            "Length",
            "Sleeve Length",
            "Shoulder Width"
        ],
        subcategories: [
            "Knitted Sweaters",
            "Turtlenecks",
            "Cardigans",
            "Cable Knit Sweaters",
            "Oversized Sweaters",
            "Fine Gauge Knits",
            "Chunky Knits"
        ],
        tags: [
            "Warm",
            "Winter",
            "Cozy",
            "Minimalist",
            "Layering",
        ]
    },
    {
        name: "Polo Shirts",
        measurements: [
            "Chest",
            "Sleeve Length",
            "Length",
            "Shoulder Width",
            "Sleeve Opening"
        ],
        material: ["Cotton", "Polyester", "Piqué Fabric"],
        subcategories: [
            "Long Sleeve Polo Shirts",
            "Classic Piqué Polo",
            "Performance Polo",
            "Rugby Shirt",
            "Interlock/Jersey Polo",
            "Fashion/Tipped Polo"
        ],
        tags: [
            "Smart Casual",
            "Breathable",
            "Sporty",
            "Comfortable",
            "Versatile",
            "Traditional",
            "Trendy",
            "Casual",
            "Summer Wear",
            "Street Style"
        ],
    },
    {
        name: "Hats & Caps",
        measurements: [
            "Circumference",
            "Height",
            "Brim Width"
        ],
        material: ["Cotton", "Wool", "Synthetic"],
        subcategories: [
            "Bucket Hats",
            "Baseball Caps",
            "Snapback Caps",
            "Fitted Caps",
            "Beanies / Knit Caps",
            "Sun Hats"
        ],
        tags: [
            "Accessories",
            "Casual",
            "Street Style",
            "Everyday Wear",
            "Functional",
            "Logo Hat",
        ],
    },
    {
        name: "Shorts",
        measurements: [
            "Waist",
            "Hips",
            "Rise",
            "Inseam",
            "Leg Opening"
        ],
        material: ["Cotton", "Polyester", "Denim"],
        subcategories: [
            "Denim Shorts",
            "Cargo Shorts",
            "Jersey Shorts",
            "Athletic Shorts",
            "Biker Shorts",
            "Sweat Shorts",
            "Tailored Shorts",
            "Beach Shorts",
            "Bermuda Shorts",
            "High-Waisted Shorts",
        ],
        tags: [
            "Summer Wear",
            "Breathable",
            "Comfortable",
            "Trendy",
            "Casual",
            "Athleisure",
        ],
    },
    {
        name: "Dresses",
        measurements: [
            "Bust",
            "Waist",
            "Hips",
            "Length",
            "Strap Length (if applicable)"
        ],
        subcategories: [
            "Maxi Dresses",
            "Midi Dresses",
            "Mini Dresses",
            "Shift Dresses",
            "Bodycon Dresses",
            "A-Line Dresses",
            "Wrap Dresses",
            "Shirt Dresses",
            "Evening Gowns",
            "Cocktail Dresses",
            "Summer Sundresses",
            "Slip Dresses",
        ],
        tags: [
            "Formal",
            "Casual",
            "Wedding Guest",
            "Date Night",
            "Elegant",
            "Floaty",
            "Floral",
            "Party Wear",
            "Bohemian",
            "Chic"
        ],
    }
];
