export const categoriesList = [
    {
        name: "T-Shirts",
        measurements: [
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Shoulder Width (cm)",
            "Sleeve Length (cm)"
        ],
        material: ["100% Cotton", "Cotton Blend", "Polyester", "Organic Cotton", "Recycled Polyester"],
        subcategories: [
            "Plain T-Shirts",
            "Graphic T-Shirts",
            "Long Sleeve T-Shirts",
            "Striped T-Shirts",
            "Henley T-Shirts",
            "Pocket T-Shirts",
        ],
        tags: [
            "Casual",
            "Everyday Wear",
            "Street Style",
            "Lightweight",
            "Comfortable",
            "Layering",
            "Breathable",
            "Athleisure",
            "Summer Wear",
        ],
    },
    {
        name: "Shirts",
        measurements: [
            "Collar Size (cm)",
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Shoulder Width (cm)",
            "Sleeve Length (cm)"
        ],
        material: ["Cotton", "Polyester", "Linen", "Silk", "Oxford Fabric", "Chambray"],
        subcategories: [
            "Formal Shirts",
            "Casual Shirts",
            "Dress Shirts",
            "Flannel Shirts",
            "Plain Shirts",
            "Printed Shirts",
            "Check Shirts",
            "Short Sleeve Shirts",
            "Denim Shirts",
        ],
        tags: [
            "Formal",
            "Smart Casual",
            "Button-Up",
            "Office Wear",
            "Versatile",
            "Breathable",
            "Stylish",
            "Comfort Fit",
        ],
    },
    {
        name: "Hoodies & Sweatshirts",
        measurements: [
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Sleeve Length (cm)",
            "Shoulder Width (cm)"
        ],
        material: ["Cotton", "Fleece", "Polyester", "Sherpa", "Knitted Fabric"],
        subcategories: [
            "Hoodies",
            "Sweatshirts",
            "Zip Hoodies",
            "Fleeces",
            "Pullover Hoodies",
        ],
        tags: [
            "Cozy",
            "Layering",
            "Streetwear",
            "Athleisure",
            "Warm",
            "Comfortable Fit",
            "Winter Wear",
        ],
    },
    {
        name: "Jackets & Coats",
        measurements: [
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Shoulder Width (cm)",
            "Sleeve Length (cm)"
        ],
        material: ["Wool", "Polyester", "Denim", "Leather", "Nylon", "Down Fill"],
        subcategories: [
            "Puffer Jackets",
            "Denim Coats",
            "Blazers",
            "Rain Coats",
            "Winter Coats",
        ],
        tags: [
            "Outerwear",
            "Weather Resistant",
            "Layering",
            "Warmth",
            "Stylish",
            "Durable",
            "Winter Wear",
        ],
    },
    {
        name: "Jeans",
        measurements: [
            "Waist (cm)",
            "Hip (cm)",
            "Inseam (cm)",
            "Outseam (cm)",
            "Thigh (cm)",
            "Leg Opening (cm)"
        ],
        material: ["100% Denim", "Stretch Denim", "Cotton", "Selvedge Denim"],
        subcategories: [
            "Straight Jeans",
            "Ripped Jeans",
            "Skinny Jeans",
            "Relaxed Fit Jeans",
            "Bootcut Jeans",
        ],
        tags: [
            "Casual",
            "Everyday Wear",
            "Durable",
            "Trendy",
            "Versatile",
            "Street Style",
            "Comfortable Fit",
        ],
    },
    {
        name: "Trousers",
        measurements: [
            "Waist (cm)",
            "Hip (cm)",
            "Inseam (cm)",
            "Outseam (cm)",
            "Thigh (cm)",
            "Leg Opening (cm)"
        ],
        material: ["Cotton", "Linen", "Polyester", "Stretch Blend"],
        subcategories: [
            "Cargo",
            "Chinos",
            "Joggers",
            "Formal Trousers",
            "Wide-Leg Trousers",
        ],
        tags: [
            "Smart Casual",
            "Chic",
            "Lightweight",
            "Versatile",
            "Comfortable",
            "Stylish",
            "Durable",
        ],
    },
    {
        name: "Skirts",
        measurements: [
            "Waist (cm)",
            "Hip (cm)",
            "Length (cm)"
        ],
        material: ["Cotton", "Polyester", "Linen", "Silk"],
        subcategories: [
            "Maxi Skirts",
            "Mini Skirts",
            "Wrap Skirts",
            "Pencil Skirts",
            "Pleated Skirts",
            "A-Line Skirts",
        ],
        tags: [
            "Fashionable",
            "Chic",
            "Lightweight",
            "Versatile",
            "Everyday Wear",
            "Stylish",
        ],
    },
    {
        name: "Co-Ord",
        measurements: [
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Hip (cm)"
        ],
        material: ["Cotton", "Polyester"],
        subcategories: [
            "Matching Tops and Bottoms",
        ],
        tags: [
            "Effortless",
            "Stylish",
            "Trendy",
            "Versatile",
            "Casual",
            "Summer Wear",
        ],
    },
    {
        name: "Polo Shirts",
        measurements: [
            "Chest (cm)",
            "Waist (cm)",
            "Length (cm)",
            "Shoulder Width (cm)",
            "Collar Size (cm)"
        ],
        material: ["Cotton", "Polyester", "Piqué Fabric"],
        subcategories: [
            "Short Sleeve Polo Shirts",
            "Long Sleeve Polo Shirts",
        ],
        tags: [
            "Smart Casual",
            "Breathable",
            "Sporty",
            "Comfortable",
            "Versatile",
        ],
    },
    {
        name: "Hats & Caps",
        measurements: [
            "Circumference (cm)",
            "Height (cm)",
            "Brim Width (cm)"
        ],
        material: ["Cotton", "Wool", "Synthetic"],
        subcategories: [
            "Beanies",
            "Bucket Hats",
            "Baseball Caps",
            "Snapback Caps",
        ],
        tags: [
            "Accessories",
            "Casual",
            "Street Style",
            "Everyday Wear",
            "Functional",
        ],
    },
    {
        name: "Accessories",
        measurements: [],
        material: ["Leather", "Synthetic", "Metal", "Plastic"],
        subcategories: [
            "Bags",
            "Belts",
            "Wallets",
            "Sunglasses",
        ],
        tags: [
            "Functional",
            "Trendy",
            "Statement Pieces",
            "Everyday Use",
        ],
    },
    {
        name: "Shorts",
        measurements: [
            "Waist (cm)",
            "Hip (cm)",
            "Inseam (cm)",
            "Outseam (cm)",
            "Thigh (cm)"
        ],
        material: ["Cotton", "Polyester", "Denim"],
        subcategories: [
            "Denim Shorts",
            "Cargo Shorts",
            "Jersey Shorts",
            "Athletic Shorts",
        ],
        tags: [
            "Summer Wear",
            "Breathable",
            "Comfortable",
            "Trendy",
            "Casual",
            "Athleisure",
        ],
    },
];
