export const categoriesList = [
    {
        name: "T-Shirts",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Plain T-Shirts",
            "Graphic T-Shirts",  
            "Long Sleeve T-Shirts",
            "Striped T-Shirts",
        ],
        tags: [
            "Casual", 
            "Everyday Wear", 
            "Street Style", 
            "Cotton", 
            "Lightweight", 
            "Comfortable", 
            "Layering", 
            "Trendy",
        ],
    },
    {
        name: "Shirts",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Plain Shirts",
            "Printed Shirts",
            "Check Shirts",
            "Short Sleeve Shirts",
            "Denim Shirts",
        ],
        tags: [
            "Smart Casual", 
            "Button-Up", 
            "Versatile", 
            "Stylish", 
            "Office Wear", 
            "Layering", 
            "Breathable", 
            "Comfort Fit",
        ],
    },
    {
        name: "Hoodies & Sweatshirts",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Hoodies",
            "Sweatshirts",
            "Zip Hoodies",
            "Fleeces",
        ],
        tags: [
            "Cozy", 
            "Casual", 
            "Layering", 
            "Athleisure", 
            "Warm", 
            "Streetwear", 
            "Comfortable Fit", 
            "Trendy",
        ],
    },
    {
        name: "Jackets & Coats",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Puffer Jackets",
            "Denim Coats",
            "Coats",
        ],
        tags: [
            "Outerwear", 
            "Warmth", 
            "Stylish", 
            "Winter", 
            "Layering", 
            "Durable", 
            "Weather Resistant", 
            "Casual",
        ],
    },
    {
        name: "Jeans",
        sizes: ["28", "30", "32", "34", "36"],
        subcategories: [
            "Straight Jeans",
            "Ripped Jeans",
        ],
        tags: [
            "Casual", 
            "Everyday Wear", 
            "Denim", 
            "Comfort Fit", 
            "Street Style", 
            "Durable", 
            "Trendy", 
            "Versatile",
        ],
    },
    {
        name: "Trousers",
        sizes: ["28", "30", "32", "34", "36"],
        subcategories: [
            "Cargo",
            "Chinos",
            "Skinny Trousers",
        ],
        tags: [
            "Smart Casual", 
            "Versatile", 
            "Comfortable", 
            "Stylish", 
            "Lightweight", 
            "Everyday Wear", 
            "Chic", 
            "Fashionable",
        ],
    },
    {
        name: "Skirts",
        sizes: ["XS", "S", "M", "L", "XL"],
        subcategories: [
            "Maxi Skirts",
            "Mini Skirts",
            "Wrap Skirts",
            "Pencil Skirts",
            "Denim Skirts",
            "Skater Skirts",
        ],
        tags: [
            "Smart Casual", 
            "Versatile", 
            "Comfortable", 
            "Stylish", 
            "Lightweight", 
            "Everyday Wear", 
            "Chic", 
            "Fashionable",
        ],
    },
    {
        name: "Co-Ord",
        sizes: ["S", "M", "L", "XL"],
        subcategories: [],
        tags: [
            "Matching Sets", 
            "Stylish", 
            "Effortless", 
            "Trendy", 
            "Versatile", 
            "Summer Wear", 
            "Casual",
        ],
    },
    {
        name: "Polo Shirts",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Long Sleeve Polo Shirts",
        ],
        tags: [
            "Smart Casual", 
            "Comfortable", 
            "Versatile", 
            "Stylish", 
            "Breathable", 
            "Sporty", 
            "Layering",
        ],
    },
    {
        name: "Hats & Caps",
        sizes: ["One Size"],
        subcategories: [
            "Beanies",
            "Bucket Hats",
            "Baseball Caps",
            "Snapback Caps",
        ],
        tags: [
            "Accessories", 
            "Trendy", 
            "Street Style", 
            "Casual", 
            "Everyday Wear", 
            "Functional", 
            "Stylish",
        ],
    },
    {
        name: "Accessories",
        sizes: ["One Size"],
        subcategories: [
            "Bags",
            "Belts",
            "Wallets",
            "Sunglasses",
        ],
        tags: [
            "Stylish", 
            "Functional", 
            "Trendy", 
            "Everyday Use", 
            "Statement Pieces", 
            "Fashionable", 
            "Street Style",
        ],
    },
    {
        name: "Shorts",
        sizes: ["S", "M", "L", "XL", "XXL"],
        subcategories: [
            "Denim Shorts",
            "Cargo Shorts",
            "Jorts",
            "Jersey Shorts",
        ],
        tags: [
            "Summer Wear", 
            "Casual", 
            "Comfortable", 
            "Breathable", 
            "Trendy", 
            "Everyday Wear", 
            "Athleisure",
        ],
    },
];
