export const PATTERNS = [
    "Abstract",
    "Adinkra",
    "Adire",
    "Adire Eleko",
    "African Wax Print",
    "Agbada",
    "Akwete",
    "Akwa-Ocha",
    "Alaari",
    "Animal Print",
    "Ankara",
    "Argyle",
    "Ashanti Kente",
    "Aso-Oke",
    "Batik",
    "Bògòlan (Bogolanfini)",
    "Bogolan (Mudcloth)",
    "Broderie Anglaise",
    "Camouflage",
    "Checkered",
    "Chevron",
    "Chitenge",
    "Damask",
    "Dashiki",
    "Ewe Kente",
    "Floral",
    "Fugu (Batakari)",
    "Geometric",
    "Ghanaian Block Print",
    "Gingham",
    "Hausa",
    "Herringbone",
    "Houndstooth",
    "Indigo Resist",
    "Isi-Agu",
    "Kanga (Khanga)",
    "Kente",
    "Kikoy (Kikoi)",
    "Kitenge",
    "Kuba Cloth",
    "Lace",
    "Lappa",
    "Leopard Print",
    "Maasai Shuka",
    "Mali Mudcloth",
    "Marble",
    "Ndebele Geometrics",
    "Nsibidi",
    "Ombre",
    "Paisley",
    "Plaid",
    "Polka Dot",
    "Sapo",
    "Senegal Woodblock Print",
    "Shweshwe",
    "Solid",
    "Striped",
    "Tartan",
    "Tie-Dye",
    "Toile",
    "Tuareg Cross",
    "Twill",
    "Waffle",
    "Wax Print",
    "Yoruba Adire",
    "Zebra Print",
    "Zulu Basketweave"
];