type Country = {
    id: number;
    name: string;
    code: string;
    flag: string;
};

export const countries: Country[] = [
    { id: 1, name: "United States", code: "+1", flag: "🇺🇸" },
    { id: 2, name: "Nigeria", code: "+234", flag: "🇳🇬" },
    { id: 3, name: "India", code: "+91", flag: "🇮🇳" },
    { id: 4, name: "United Kingdom", code: "+44", flag: "🇬🇧" },
    { id: 5, name: "Canada", code: "+1", flag: "🇨🇦" },
    { id: 6, name: "Australia", code: "+61", flag: "🇦🇺" },
    { id: 7, name: "Germany", code: "+49", flag: "🇩🇪" },
    { id: 8, name: "France", code: "+33", flag: "🇫🇷" },
    { id: 9, name: "South Africa", code: "+27", flag: "🇿🇦" },
    { id: 10, name: "Japan", code: "+81", flag: "🇯🇵" },
    { id: 11, name: "China", code: "+86", flag: "🇨🇳" },
    { id: 12, name: "Brazil", code: "+55", flag: "🇧🇷" },
    { id: 13, name: "Mexico", code: "+52", flag: "🇲🇽" },
    { id: 14, name: "Italy", code: "+39", flag: "🇮🇹" },
    { id: 15, name: "Spain", code: "+34", flag: "🇪🇸" },
    { id: 16, name: "Russia", code: "+7", flag: "🇷🇺" },
    { id: 17, name: "South Korea", code: "+82", flag: "🇰🇷" },
    { id: 18, name: "Indonesia", code: "+62", flag: "🇮🇩" },
    { id: 19, name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
    { id: 20, name: "Turkey", code: "+90", flag: "🇹🇷" },
    { id: 21, name: "Pakistan", code: "+92", flag: "🇵🇰" },
    { id: 22, name: "Bangladesh", code: "+880", flag: "🇧🇩" },
    { id: 23, name: "Argentina", code: "+54", flag: "🇦🇷" },
    { id: 24, name: "Egypt", code: "+20", flag: "🇪🇬" },
    { id: 25, name: "Vietnam", code: "+84", flag: "🇻🇳" },
    { id: 26, name: "Philippines", code: "+63", flag: "🇵🇭" },
    { id: 27, name: "Thailand", code: "+66", flag: "🇹🇭" },
    { id: 28, name: "Singapore", code: "+65", flag: "🇸🇬" },
    { id: 29, name: "Netherlands", code: "+31", flag: "🇳🇱" },
    { id: 30, name: "Sweden", code: "+46", flag: "🇸🇪" },
    { id: 31, name: "Norway", code: "+47", flag: "🇳🇴" },
    { id: 32, name: "Denmark", code: "+45", flag: "🇩🇰" },
    { id: 33, name: "Switzerland", code: "+41", flag: "🇨🇭" },
    { id: 34, name: "Poland", code: "+48", flag: "🇵🇱" },
    { id: 35, name: "Portugal", code: "+351", flag: "🇵🇹" },
    { id: 36, name: "Greece", code: "+30", flag: "🇬🇷" },
    { id: 37, name: "Ukraine", code: "+380", flag: "🇺🇦" },
    { id: 38, name: "Austria", code: "+43", flag: "🇦🇹" },
    { id: 39, name: "Israel", code: "+972", flag: "🇮🇱" },
    { id: 40, name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
    { id: 41, name: "New Zealand", code: "+64", flag: "🇳🇿" },
    { id: 42, name: "Ireland", code: "+353", flag: "🇮🇪" },
    { id: 43, name: "Belgium", code: "+32", flag: "🇧🇪" },
    { id: 44, name: "Czech Republic", code: "+420", flag: "🇨🇿" },
    { id: 45, name: "Hungary", code: "+36", flag: "🇭🇺" },
    { id: 46, name: "Finland", code: "+358", flag: "🇫🇮" },
    { id: 47, name: "Chile", code: "+56", flag: "🇨🇱" },
    { id: 48, name: "Colombia", code: "+57", flag: "🇨🇴" },
    { id: 49, name: "Peru", code: "+51", flag: "🇵🇪" },
    { id: 50, name: "Venezuela", code: "+58", flag: "🇻🇪" },
    { id: 51, name: "Ethiopia", code: "+251", flag: "🇪🇹" },
    { id: 52, name: "Ghana", code: "+233", flag: "🇬🇭" },
    { id: 53, name: "Kenya", code: "+254", flag: "🇰🇪" },
    { id: 54, name: "Uganda", code: "+256", flag: "🇺🇬" },
    { id: 55, name: "Tanzania", code: "+255", flag: "🇹🇿" },
    { id: 56, name: "Zimbabwe", code: "+263", flag: "🇿🇼" },
    { id: 57, name: "Morocco", code: "+212", flag: "🇲🇦" },
    { id: 58, name: "Algeria", code: "+213", flag: "🇩🇿" },
];
