export type Country = {
    name: string;
    code: string;
    alpha2: string; // Added alpha2 code
    flag: string;
};

export const countries: Country[] = [ 
    { name: "Algeria", code: "+213", alpha2: "DZ", flag: "🇩🇿" },
    { name: "Argentina", code: "+54", alpha2: "AR", flag: "🇦🇷" },
    { name: "Australia", code: "+61", alpha2: "AU", flag: "🇦🇺" },
    { name: "Austria", code: "+43", alpha2: "AT", flag: "🇦🇹" },
    { name: "Bangladesh", code: "+880", alpha2: "BD", flag: "🇧🇩" },
    { name: "Belgium", code: "+32", alpha2: "BE", flag: "🇧🇪" },
    { name: "Brazil", code: "+55", alpha2: "BR", flag: "🇧🇷" },
    { name: "Canada", code: "+1", alpha2: "CA", flag: "🇨🇦" },
    { name: "Chile", code: "+56", alpha2: "CL", flag: "🇨🇱" },
    { name: "China", code: "+86", alpha2: "CN", flag: "🇨🇳" },
    { name: "Colombia", code: "+57", alpha2: "CO", flag: "🇨🇴" },
    { name: "Czech Republic", code: "+420", alpha2: "CZ", flag: "🇨🇿" },
    { name: "Denmark", code: "+45", alpha2: "DK", flag: "🇩🇰" },
    { name: "Egypt", code: "+20", alpha2: "EG", flag: "🇪🇬" },
    { name: "Ethiopia", code: "+251", alpha2: "ET", flag: "🇪🇹" },
    { name: "Finland", code: "+358", alpha2: "FI", flag: "🇫🇮" },
    { name: "France", code: "+33", alpha2: "FR", flag: "🇫🇷" },
    { name: "Germany", code: "+49", alpha2: "DE", flag: "🇩🇪" },
    { name: "Ghana", code: "+233", alpha2: "GH", flag: "🇬🇭" },
    { name: "Greece", code: "+30", alpha2: "GR", flag: "🇬🇷" },
    { name: "Hungary", code: "+36", alpha2: "HU", flag: "🇭🇺" },
    { name: "India", code: "+91", alpha2: "IN", flag: "🇮🇳" },
    { name: "Indonesia", code: "+62", alpha2: "ID", flag: "🇮🇩" },
    { name: "Ireland", code: "+353", alpha2: "IE", flag: "🇮🇪" },
    { name: "Israel", code: "+972", alpha2: "IL", flag: "🇮🇱" },
    { name: "Italy", code: "+39", alpha2: "IT", flag: "🇮🇹" },
    { name: "Japan", code: "+81", alpha2: "JP", flag: "🇯🇵" },
    { name: "Kenya", code: "+254", alpha2: "KE", flag: "🇰🇪" },
    { name: "Mexico", code: "+52", alpha2: "MX", flag: "🇲🇽" },
    { name: "Morocco", code: "+212", alpha2: "MA", flag: "🇲🇦" },
    { name: "Netherlands", code: "+31", alpha2: "NL", flag: "🇳🇱" },
    { name: "New Zealand", code: "+64", alpha2: "NZ", flag: "🇳🇿" },
    { name: "Nigeria", code: "+234", alpha2: "NG", flag: "🇳🇬" },
    { name: "Norway", code: "+47", alpha2: "NO", flag: "🇳🇴" },
    { name: "Pakistan", code: "+92", alpha2: "PK", flag: "🇵🇰" },
    { name: "Peru", code: "+51", alpha2: "PE", flag: "🇵🇪" },
    { name: "Philippines", code: "+63", alpha2: "PH", flag: "🇵🇭" },
    { name: "Poland", code: "+48", alpha2: "PL", flag: "🇵🇱" },
    { name: "Portugal", code: "+351", alpha2: "PT", flag: "🇵🇹" },
    { name: "Russia", code: "+7", alpha2: "RU", flag: "🇷🇺" },
    { name: "Saudi Arabia", code: "+966", alpha2: "SA", flag: "🇸🇦" },
    { name: "Singapore", code: "+65", alpha2: "SG", flag: "🇸🇬" },
    { name: "South Africa", code: "+27", alpha2: "ZA", flag: "🇿🇦" },
    { name: "South Korea", code: "+82", alpha2: "KR", flag: "🇰🇷" },
    { name: "Spain", code: "+34", alpha2: "ES", flag: "🇪🇸" },
    { name: "Sweden", code: "+46", alpha2: "SE", flag: "🇸🇪" },
    { name: "Switzerland", code: "+41", alpha2: "CH", flag: "🇨🇭" },
    { name: "Tanzania", code: "+255", alpha2: "TZ", flag: "🇹🇿" },
    { name: "Thailand", code: "+66", alpha2: "TH", flag: "🇹🇭" },
    { name: "Türkiye", code: "+90", alpha2: "TR", flag: "🇹🇷" },
    { name: "Uganda", code: "+256", alpha2: "UG", flag: "🇺🇬" },
    { name: "Ukraine", code: "+380", alpha2: "UA", flag: "🇺🇦" },
    { name: "United Arab Emirates", code: "+971", alpha2: "AE", flag: "🇦🇪" },
    { name: "United Kingdom", code: "+44", alpha2: "GB", flag: "🇬🇧" },
    { name: "United States", code: "+1", alpha2: "US", flag: "🇺🇸" },
    { name: "Venezuela", code: "+58", alpha2: "VE", flag: "🇻🇪" },
    { name: "Vietnam", code: "+84", alpha2: "VN", flag: "🇻🇳" },
    { name: "Zimbabwe", code: "+263", alpha2: "ZW", flag: "🇿🇼" },
];

export const brandCountries: Country[] = [
    { name: "Nigeria", code: "+234", alpha2: "NG", flag: "🇳🇬" },
    { name: "Ghana", code: "+233", alpha2: "GH", flag: "🇬🇭" },
    { name: "Kenya", code: "+254", alpha2: "KE", flag: "🇰🇪" },
    { name: "South Africa", code: "+27", alpha2: "ZA", flag: "🇿🇦"},
    { name: "Tanzania", code: "+255", alpha2: "TZ", flag: "🇹🇿"},
    { name: "Uganda", code: "+256", alpha2: "UG", flag: "🇺🇬"},
]