export const clothingMaterials = [
    "Acrylic",
    "Adire Cloth",
    "Akwete Cloth",
    "Alaari Silk",
    "Ankara (African Wax Print)",
    "Aso-Oke",
    "Bamboo",
    "Barkcloth",
    "Batiste",
    "Batik Fabric",
    "Bògòlanfini (Mudcloth)",
    "Bouclé",
    "Broadcloth",
    "Calico",
    "Canvas",
    "Cashmere",
    "Chambray",
    "Charmeuse",
    "Chenille",
    "Chiffon",
    "Corduroy",
    "Cotton",
    "Crepe",
    "Damask",
    "Dashiki Fabric",
    "Denim",
    "Down Fill",
    "Dupioni",
    "Ewe Kente",
    "Faille",
    "Flannel",
    "Fleece",
    "Fugu Cloth (Smock Fabric)",
    "Gabardine",
    "Georgette",
    "Gingham",
    "Grosgrain",
    "Hemp",
    "Herringbone",
    "Houndstooth",
    "Interlock",
    "Jacquard",
    "Jersey",
    "Kanga Cloth",
    "Kente Cloth",
    "Kikoy Fabric",
    "Kitenge/Chitenge",
    "Knitted Fabric",
    "Kuba Cloth (Raffia)",
    "Lace",
    "Leather",
    "Linen",
    "Matelassé",
    "Mesh",
    "Modal",
    "Moire",
    "Muslin",
    "Nylon",
    "Organdy",
    "Organza",
    "Oxford",
    "Piqué",
    "Plissé",
    "Polyester",
    "Poplin",
    "Raffia",
    "Rayon",
    "Satin",
    "Sateen",
    "Seersucker",
    "Selvedge Denim",
    "Shantung",
    "Sherpa",
    "Shweshwe",
    "Silk",
    "Spandex",
    "Stretch Denim",
    "Suede",
    "Taffeta",
    "Tartan",
    "Terrycloth",
    "Tweed",
    "Tulle",
    "Velour",
    "Velvet",
    "Viscose",
    "Whipcord",
    "Wool",
    "Worsted",
    "Zibeline"
];